### ISSUE TITLE
error in install whisper

### ISSUE THREAD

**Issue by mahdiseyed2** [karaage0703/whisper-docker#1]
mahdi@mahdi-virtual-machine:~/whisper-docker$ sudo  docker build -t whisper .
[sudo] password for mahdi:
[+] Building 361.6s (8/8) FINISHED                                                                                                                                            docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                    0.0s
 => => transferring dockerfile: 305B                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                                                                                      3.6s
 => [internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [1/5] FROM docker.io/library/python:3.9-slim@sha256:088d9217202188598aac37f8db0929345e124a82134ac66b8bb50ee9750b045b                                                                0.0s
 => CACHED [2/5] WORKDIR /workspace                                                                                                                                                     0.0s
 => CACHED [3/5] RUN apt-get update && apt-get install -y     build-essential     gcc     git     ffmpeg     && rm -rf /var/lib/apt/lists/*                                             0.0s
 => CACHED [4/5] RUN pip install --upgrade pip                                                                                                                                          0.0s
 => ERROR [5/5] RUN pip install git+https://github.com/openai/whisper.git                                                                                                             357.7s
------
 > [5/5] RUN pip install git+https://github.com/openai/whisper.git:
2.474 Collecting git+https://github.com/openai/whisper.git
2.482   Cloning https://github.com/openai/whisper.git to /tmp/pip-req-build-fn1a6obh
2.512   Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git /tmp/pip-req-build-fn1a6obh
12.55   Resolved https://github.com/openai/whisper.git to commit ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab
12.61   Installing build dependencies: started
22.92   Installing build dependencies: finished with status 'done'
22.94   Getting requirements to build wheel: started
24.74   Getting requirements to build wheel: finished with status 'done'
24.75   Installing backend dependencies: started
30.62   Installing backend dependencies: finished with status 'done'
30.63   Preparing metadata (pyproject.toml): started
32.07   Preparing metadata (pyproject.toml): finished with status 'done'
34.40 Collecting numba (from openai-whisper==20231117)
35.44   Downloading numba-0.59.1-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.7 kB)
37.40 Collecting numpy (from openai-whisper==20231117)
37.53   Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
37.77      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 248.7 kB/s eta 0:00:00
38.37 Collecting torch (from openai-whisper==20231117)
38.50   Downloading torch-2.3.0-cp39-cp39-manylinux1_x86_64.whl.metadata (26 kB)
39.29 Collecting tqdm (from openai-whisper==20231117)
39.42   Downloading tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
39.55      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 433.6 kB/s eta 0:00:00
39.96 Collecting more-itertools (from openai-whisper==20231117)
40.19   Downloading more_itertools-10.2.0-py3-none-any.whl.metadata (34 kB)
40.74 Collecting tiktoken (from openai-whisper==20231117)
40.97   Downloading tiktoken-0.7.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
41.44 Collecting triton<3,>=2.0.0 (from openai-whisper==20231117)
41.65   Downloading triton-2.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
42.07 Collecting filelock (from triton<3,>=2.0.0->openai-whisper==20231117)
42.24   Downloading filelock-3.14.0-py3-none-any.whl.metadata (2.8 kB)
43.23 Collecting llvmlite<0.43,>=0.42.0dev0 (from numba->openai-whisper==20231117)
43.35   Downloading llvmlite-0.42.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
47.05 Collecting regex>=2022.1.18 (from tiktoken->openai-whisper==20231117)
47.17   Downloading regex-2024.5.10-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
47.41      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 260.2 kB/s eta 0:00:00
47.95 Collecting requests>=2.26.0 (from tiktoken->openai-whisper==20231117)
48.08   Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
48.82 Collecting typing-extensions>=4.8.0 (from torch->openai-whisper==20231117)
48.98   Downloading typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
49.49 Collecting sympy (from torch->openai-whisper==20231117)
49.62   Downloading sympy-1.12-py3-none-any.whl.metadata (12 kB)
50.20 Collecting networkx (from torch->openai-whisper==20231117)
50.33   Downloading networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
50.81 Collecting jinja2 (from torch->openai-whisper==20231117)
50.97   Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
51.48 Collecting fsspec (from torch->openai-whisper==20231117)
51.66   Downloading fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
52.08 Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch->openai-whisper==20231117)
52.33   Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
52.77 Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch->openai-whisper==20231117)
53.02   Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
53.46 Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch->openai-whisper==20231117)
53.60   Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
54.04 Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch->openai-whisper==20231117)
54.19   Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
54.63 Collecting nvidia-cublas-cu12==12.1.3.1 (from torch->openai-whisper==20231117)
54.88   Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
55.17 Collecting nvidia-cufft-cu12==11.0.2.54 (from torch->openai-whisper==20231117)
55.39   Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
55.72 Collecting nvidia-curand-cu12==10.3.2.106 (from torch->openai-whisper==20231117)
55.86   Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
56.33 Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch->openai-whisper==20231117)
56.52   Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
57.03 Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch->openai-whisper==20231117)
57.19   Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
57.61 Collecting nvidia-nccl-cu12==2.20.5 (from torch->openai-whisper==20231117)
57.75   Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
58.20 Collecting nvidia-nvtx-cu12==12.1.105 (from torch->openai-whisper==20231117)
58.38   Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
58.98 Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch->openai-whisper==20231117)
59.12   Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
60.29 Collecting charset-normalizer<4,>=2 (from requests>=2.26.0->tiktoken->openai-whisper==20231117)
60.51   Downloading charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
60.93 Collecting idna<4,>=2.5 (from requests>=2.26.0->tiktoken->openai-whisper==20231117)
61.07   Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
61.79 Collecting urllib3<3,>=1.21.1 (from requests>=2.26.0->tiktoken->openai-whisper==20231117)
61.92   Downloading urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
62.44 Collecting certifi>=2017.4.17 (from requests>=2.26.0->tiktoken->openai-whisper==20231117)
62.59   Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
63.70 Collecting MarkupSafe>=2.0 (from jinja2->torch->openai-whisper==20231117)
63.84   Downloading MarkupSafe-2.1.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
64.45 Collecting mpmath>=0.19 (from sympy->torch->openai-whisper==20231117)
64.63   Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
65.19 Downloading triton-2.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (168.1 MB)
96.15    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.1/168.1 MB 5.8 MB/s eta 0:00:00
96.30 Downloading more_itertools-10.2.0-py3-none-any.whl (57 kB)
96.35    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 1.6 MB/s eta 0:00:00
96.53 Downloading numba-0.59.1-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
97.64    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 3.4 MB/s eta 0:00:00
97.78 Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
103.8    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 3.0 MB/s eta 0:00:00
104.0 Downloading tiktoken-0.7.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
104.5    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.2 MB/s eta 0:00:00
104.6 Downloading torch-2.3.0-cp39-cp39-manylinux1_x86_64.whl (779.1 MB)
261.8    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 779.1/779.1 MB 1.5 MB/s eta 0:00:00
262.0 Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
355.9    ━━━━━━━━━━━━━━━━━━━━━━━━━━              277.2/410.6 MB 471.2 kB/s eta 0:04:44
356.0 ERROR: Exception:
356.0 Traceback (most recent call last):
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
356.0     yield
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
356.0     data = self._fp_read(amt) if not fp_closed else b""
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
356.0     return self._fp.read(amt) if amt is not None else self._fp.read()
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
356.0     data: bytes = self.__fp.read(amt)
356.0   File "/usr/local/lib/python3.9/http/client.py", line 463, in read
356.0     n = self.readinto(b)
356.0   File "/usr/local/lib/python3.9/http/client.py", line 507, in readinto
356.0     n = self.fp.readinto(b)
356.0   File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
356.0     return self._sock.recv_into(b)
356.0   File "/usr/local/lib/python3.9/ssl.py", line 1275, in recv_into
356.0     return self.read(nbytes, buffer)
356.0   File "/usr/local/lib/python3.9/ssl.py", line 1133, in read
356.0     return self._sslobj.read(len, buffer)
356.0 socket.timeout: The read operation timed out
356.0
356.0 During handling of the above exception, another exception occurred:
356.0
356.0 Traceback (most recent call last):
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
356.0     status = run_func(*args)
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
356.0     return func(self, options, args)
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 377, in run
356.0     requirement_set = resolver.resolve(
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
356.0     self.factory.preparer.prepare_linked_requirements_more(reqs)
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 552, in prepare_linked_requirements_more
356.0     self._complete_partial_requirements(
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 467, in _complete_partial_requirements
356.0     for link, (filepath, _) in batch_download:
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/download.py", line 183, in __call__
356.0     for chunk in chunks:
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
356.0     for chunk in iterable:
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
356.0     for chunk in response.raw.stream(
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
356.0     data = self.read(amt=amt, decode_content=decode_content)
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
356.0     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
356.0   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
356.0     self.gen.throw(typ, value, traceback)
356.0   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
356.0     raise ReadTimeoutError(self._pool, None, "Read timed out.")
356.0 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
------
Dockerfile:14
--------------------
  12 |     RUN pip install --upgrade pip
  13 |
  14 | >>> RUN pip install git+https://github.com/openai/whisper.git
  15 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install git+https://github.com/openai/whisper.git" did not complete successfully: exit code: 2

**Comment by mahdiseyed2** [comment]
error in install whisper in ubuntu 22
